[package]
name = "insomnia-rs"
version = "0.2.0"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
clap = {version = "2.33.0", features = ["yaml"]}
fern = "0.5.8"
lazy_static = "1.3.0"
log = "0.4.7"
regex = "1.1.9"
