# option to redirect the files which are generated to a specific output directory. if no value is set explicitly,
# the default is used (the current directory where the executable is ran).
# data_directory = "/tmp"

# define the audio devices which should be used for recording. These devices are used simutaniously for recording
# audio
[input.first_audio_device]
card = 3
device = 0
mono = false

# this would be the second device. The name of the section does not matter and should be descriptive
[input.second_audio_device]
card = 4
device = 0
mono = false
