[package]
name = "insomnia"
version = "0.4.0"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[lib]
name = "insomnia"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.11"
lazy_static = "1.4.0"
log = "0.4.8"
regex = "1.3.7"
