[package]
name = "insomnia"
version = "0.3.1"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[lib]
name = "insomnia"
path = "src/lib.rs"

[dependencies]
chrono = "0.4"
lazy_static = "1.3"
log = "0.4"
regex = "1.2"
