[package]
name = "insomnia"
version = "0.4.0"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[lib]
name = "insomnia"
path = "src/lib.rs"

[dependencies]
chrono = "*"
lazy_static = "*"
log = "*"
regex = "*"
