[package]
name = "schlaflosigkeit"
version = "0.3.0"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"

[dependencies]
chrono = "0.4.7"
clap = {version = "2.33.0", features = ["yaml"]}
fern = "0.5.8"
insomnia = { path = "../insomnia" }
log = "0.4.7"
